"use strict";
var ArtefactData = (function () {
    function ArtefactData() {
        this.list = [
            { name: "- Artefacts -", pts: 0, validTypes: [], description: '' },
            { name: "Blade of Slashing", pts: 5, validTypes: [], description: '' },
            { name: "Fire Oil", pts: 5, validTypes: [], description: '' },
            { name: "Kevinar's Flying Hammer", pts: 5, validTypes: [], description: 'The unit has a ranged attack for which you roll a sing die, regardless of the Attacks value of the unit.  This attack has a range of 12" and always hits on a 4+, regardless of modifiers, and if a hit is scored, it is resolved at Piercing(2).' },
            { name: "Mace of Crushing", pts: 5, validTypes: [], description: '' },
            { name: "War-bow of Kaba", pts: 5, validTypes: [], description: '' },
            { name: "Dwarven Ale", pts: 10, validTypes: [], description: '' },
            { name: "Myrddin's Amulet of the Fireheart", pts: 10, validTypes: [], description: '' },
            { name: "Piercing Arrow", pts: 10, validTypes: [], description: '' },
            { name: "Quicksilver Rapier", pts: 10, validTypes: [], description: '' },
            { name: "Brew of Courage", pts: 15, validTypes: [], description: '' },
            { name: "Brew of Haste", pts: 15, validTypes: [], description: '' },
            { name: "Pipes of Terror", pts: 15, validTypes: [], description: '' },
            { name: "Blade of the Beast Slayer", pts: 20, validTypes: [], description: '' },
            { name: "Darklord's Onyx Ring", pts: 20, validTypes: [], description: '' },
            { name: "Helm of Confidence", pts: 20, validTypes: [], description: '' },
            { name: "Maccwar's Potion of the Caterpillar", pts: 20, validTypes: [], description: 'The unit has the Pathfinder special rule.' },
            { name: "Talisman of Inspiration", pts: 20, validTypes: [], description: '' },
            { name: "Blessing of the Gods", pts: 25, validTypes: [], description: 'The unit has the Elite special rule.' },
            { name: "Chant of Hate", pts: 25, validTypes: [], description: 'The unit has the Vicious special rule.' },
            { name: "Kaba's Holy Hand Grenades", pts: 25, validTypes: [], description: '' },
            { name: "Scarletmaw's Fenulian Amulet", pts: 25, validTypes: [], description: '' },
            { name: "Boots of Levitation", pts: 30, validTypes: [], description: '' },
            { name: "Brew of Strength", pts: 30, validTypes: [], description: 'The unit has Crushing Strength (1), or if trhe unit already has Crushing Strength, it is increased by 1.' },
            { name: "Crepognon's Scrying Gem of Zellak", pts: 30, validTypes: [], description: '' },
            { name: "Diadem of Dragon-kind", pts: 30, validTypes: [], description: 'The unit has the Breath Attack (10) special rule.' },
            { name: "Healing Charm", pts: 30, validTypes: [], description: '' },
            { name: "Heart-seeking Chant", pts: 30, validTypes: [], description: '' },
            { name: "Mreb's Grimoire of Unspeakable Darkness", pts: 30, validTypes: [], description: '' },
            { name: "The Boomstick", pts: 30, validTypes: [], description: '' },
            { name: "Boots of the Seven Leagues", pts: 35, validTypes: [], description: '' },
            { name: "Jar of the Four Winds", pts: 35, validTypes: [], description: '' },
            // { name: "Ensorcelled Armor",                        pts: 35, validTypes: [], description: '' },
            // { name: "Medallion of Life",                        pts: 35, validTypes: [], description: '' },
            { name: "Orcsbain's Amulet of Thorns", pts: 35, validTypes: [], description: '' },
            { name: "The Fog", pts: 35, validTypes: [], description: '' },
            { name: "Wine of Elvenkind", pts: 40, validTypes: [], description: '' },
            { name: "Wings of the Honeymaze", pts: 40, validTypes: [], description: '' },
            // { name: "Brew of Keen-eyeness",                     pts: 45, validTypes: [], description: '' },
            { name: "Brew of Sharpness", pts: 45, validTypes: [], description: '' },
            { name: "Crystal Pendant of Retribution", pts: 50, validTypes: [], description: '' },
            { name: "Healing Brew", pts: 5, validTypes: [], description: '' },
            { name: "Sparkstone", pts: 10, validTypes: [], description: '' },
            { name: "Helm of the Ram", pts: 15, validTypes: [], description: '' },
            { name: "Blood of the Old King", pts: 15, validTypes: [], description: 'During one round of combat, grants the unit has Elite and Vicious special rules.' },
            { name: "Banner of the Griffin", pts: 20, validTypes: [], description: '' },
            { name: "Dragonshard Shield", pts: 20, validTypes: [], description: '' },
            { name: "Hammer of Measured Force", pts: 20, validTypes: [], description: '' },
            { name: "Lute of Insatiable Darkness", pts: 20, validTypes: [], description: '' },
            { name: "Zephyr Crown", pts: 20, validTypes: [], description: '' },
            { name: "Shroud of the Saint", pts: 25, validTypes: [], description: '' },
        ];
    }
    return ArtefactData;
}());
exports.ArtefactData = ArtefactData;
//# sourceMappingURL=artefacts.data.js.map